# Generated by Django 3.2.3 on 2023-10-14 12:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
        ('carts', '0002_auto_20231014_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Cart',
        ),
    ]
