# Generated by Django 3.2.3 on 2024-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240415_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за 100г'),
        ),
    ]
